import type { LessonData } from "../types";

const content: LessonData = {
  num: 17,
  orderIndex: 2,
  phaseLabel: "LLM APIS + TOKENS + COST",
  title: "It's a Transcript, Not a Textbox: Structuring a Chat Call",
  minutes: 18,
  concept:
    "A chat API call isn't one long string — it's a list of message dicts, each one shaped like {\"role\": \"user\", \"content\": \"...\"}. The role tells the model who is speaking: \"system\" sets up how the model should behave for the whole conversation, \"user\" is what the human typed, and \"assistant\" is what the model said back. When you call the API, you send the entire list of messages so far, and the model reads all of it as context before generating its reply — that reply is the \"completion,\" and it comes back as a new assistant message you append to the same list. To continue the conversation, you don't start over: you add the user's next message onto that growing list and send the whole thing again, which is exactly why longer conversations cost more tokens with every turn. The list itself is the conversation's memory — the model has no memory of its own between calls, so whatever isn't in that list didn't happen as far as it's concerned.",
  conceptSimpler:
    "A chat API call is like handing someone the entire transcript of a conversation before asking them to say the next line — they don't remember yesterday's chat, so you have to hand them the whole script every single time.",
  vizStages: [
    {
      label: "1. One message is just a dict",
      body:
        "The smallest building block is a dict with two keys: who's talking, and what they said. Nothing fancier than that.",
      code: "{\"role\": \"user\", \"content\": \"My order hasn't arrived yet.\"}",
    },
    {
      label: "2. A conversation is a list of them",
      body:
        "A real request sends a list of these dicts in order. The system message (if there is one) usually comes first and sets the tone for everything that follows.",
      code:
        "messages = [\n  {\"role\": \"system\", \"content\": \"You are a support agent.\"},\n  {\"role\": \"user\", \"content\": \"My order hasn't arrived yet.\"}\n]",
    },
    {
      label: "3. The completion is the model's reply",
      body:
        "The API doesn't return a whole new conversation — it returns one new message, generated by the model, that continues the list you sent.",
      code: "{\"role\": \"assistant\", \"content\": \"I'm sorry to hear that — can you share your order number?\"}",
    },
    {
      label: "4. You append it and send again",
      body:
        "To keep the conversation going, that assistant reply gets appended to the list, then the user's next message gets appended too, and the whole thing is sent again on the next call.",
      code:
        "messages.append(assistant_reply)\nmessages.append({\"role\": \"user\", \"content\": \"It's ORD-4471.\"})",
    },
  ],
  realWorldIntro:
    "OpenAI's chat completions API and Anthropic's messages API both work exactly this way — you POST a messages array of role/content pairs, and the response contains one new message to add back onto that array before your next call.",
  realWorldCode:
    "response = client.chat.completions.create(\n  model=\"gpt-4o-mini\",\n  messages=messages\n)",
  sandbox: {
    kind: "code",
    challenge:
      "Build a growing list of message dicts representing a multi-turn support conversation, then check whether it ends on a user turn.",
    starterCode:
      "def make_message(role, content):\n    return {\"role\": role, \"content\": content}\n\nmessages = []\nmessages.append(make_message(\"system\", \"You are a helpful support assistant.\"))\nmessages.append(make_message(\"user\", \"My order hasn't arrived yet.\"))\nmessages.append(make_message(\"assistant\", \"I'm sorry to hear that. Can you share your order number?\"))\nmessages.append(make_message(\"user\", \"It's ORD-4471.\"))\n\nfor m in messages:\n    print(m[\"role\"], \":\", m[\"content\"])\n\nuser_turns = 0\nfor m in messages:\n    if m[\"role\"] == \"user\":\n        user_turns = user_turns + 1\n\nprint(\"user turns so far:\", user_turns)\n\nlast_index = len(messages) - 1\nlast_message = messages[last_index]\n\nif last_message[\"role\"] == \"user\":\n    print(\"ready to call the API for a new assistant reply\")\nelse:\n    print(\"already ended on an assistant turn\")",
  },
  quizQuestion:
    "This code builds a messages list and checks the role of the last entry before calling the API. What does last_role(messages) print, and why does that matter for a chat completion call?",
  quizCode:
    "messages = []\nmessages.append({\"role\": \"system\", \"content\": \"You are terse.\"})\nmessages.append({\"role\": \"user\", \"content\": \"What's 2+2?\"})\n\ndef last_role(msgs):\n    last_index = len(msgs) - 1\n    last_message = msgs[last_index]\n    return last_message[\"role\"]\n\nprint(last_role(messages))",
  quizOptions: [
    {
      key: "a",
      label:
        "\"user\" — a chat API call expects the list to end on a user (or tool) turn, since it's generating the next assistant reply to respond to that",
      correct: true,
    },
    {
      key: "b",
      label: "\"system\" — the system message always counts as the most recent entry no matter what's appended after it",
      correct: false,
    },
    {
      key: "c",
      label: "\"assistant\" — every conversation is required to end on an assistant message before you can send it",
      correct: false,
    },
  ],
  quizFeedbackCorrect:
    "Right — the last entry appended was the user's question, so last_role returns \"user\"; sending the list now makes sense, since the model has something fresh to respond to and its reply becomes the next assistant message.",
  quizFeedbackIncorrect:
    "Not quite — messages append in order, and \"user\" was the last one added here, not \"system\" or \"assistant\"; a chat call is meant to end on a user (or tool) turn so the model has something new to reply to.",
  takeaway:
    "A chat API call is a list of role/content dicts, not a single string — the model reads the whole list as context and returns one new assistant message, which you append before sending the growing list again on the next turn.",
};

export default content;
